alerting/urls.py
from . import views

from django.urls import path


app_name = 'alerting'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.index, name='index'),
    path('validating/', views.ValidatingView.as_view(), name='validating'),
    path('published/', views.PublishedView.as_view(), name='published'),
    path('declined/', views.DeclinedView.as_view(), name='declined'),
    path('jobs/', views.JobsView.as_view(), name='jobs'),
]

opencoinwatch/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('alerting.urls')),
    # path('admin/', admin.site.urls),
]

alerting/models.py
from opencoinwatch import config
from alerting import common_utils
from alerting import production

from django.db.models import Q
from django.db import models

import datetime
import pytz


class Alert(models.Model):
    generated_time = models.DateTimeField()
    referenced_time = models.DateTimeField()
    symbol = models.CharField(max_length=64)
    current_exchange_rate = models.FloatField()
    referenced_exchange_rate = models.FloatField()
    published = models.BooleanField(default=False)
    declined = models.BooleanField(default=False)
    published_time = models.DateTimeField(null=True, blank=True)
    published_text = models.TextField(blank=True)

    def publish(self):
        assert self.is_validating()
        self.published = True
        self.published_time = datetime.datetime.now(pytz.timezone('Europe/Prague'))
        text = self.get_text()
        production.post_tweet(text)
        production.send_pushover_notification(text)
        self.published_text = text
        self.save()

    def prepare_for_validation(self):
        alerts_existed = False
        existing_alerts = Alert.get_all_validating_alerts(self.symbol)
        if existing_alerts.exists():
            existing_alerts.delete()
            alerts_existed = True

        self.save()

        if not alerts_existed:
            production.send_pushover_notification("New alert waiting for validation.")

    def decline(self):
        assert self.is_validating()
        self.declined = True
        self.save()

    def is_validating(self):
        return self.published == False and self.declined == False

    def get_importance(self):
        percentual_change = self.get_percentual_change()
        limit = common_utils.percentage_limit(self.get_time_difference_minutes())
        return abs(percentual_change / limit)

    def get_importance_with_handicap(self):
        importance = self.get_importance()
        handicap = self.get_handicap()
        return importance / handicap

    def get_handicap(self):
        return Alert.get_handicap_for_symbol(self.symbol, self.current_exchange_rate)

    def get_percentual_change(self):
        relative_change = self.current_exchange_rate / self.referenced_exchange_rate
        percentual_change = (relative_change - 1) * 100
        return percentual_change

    def get_time_difference_minutes(self):
        return (self.generated_time - self.referenced_time).total_seconds() / 60

    def get_emoji(self):
        if self.get_percentual_change() > 0:
            return "☀️"  # Sunny
        elif self.get_importance_with_handicap() < 2:
            return "☁️"  # Cloudy
        else:
            return "🌧️"  # Rain

    def get_text(self):
        percentual_change_raw = self.get_percentual_change()

        symbol = self.symbol
        direction = "UP" if percentual_change_raw > 0 else "DOWN"
        emoji = self.get_emoji()
        percentual_change = common_utils.smart_float_format(abs(percentual_change_raw))
        time_difference = common_utils.smart_time_duration_format(self.get_time_difference_minutes())
        exchange_rate = common_utils.smart_float_format(self.current_exchange_rate)
        tags = " ".join(config.SYMBOLS[self.symbol]['tags'])
        link = f"https://coinmarketcap.com/currencies/{config.SYMBOLS[self.symbol]['coinmarketcap']}/"

        return f"{symbol} {direction} {emoji} by {percentual_change}% in the last {time_difference}, now at {exchange_rate} USDT {tags} {link}"

    @staticmethod
    def get_last_published_or_declined_alert_generated_time(symbol):
        symbols_match = Q(symbol=symbol)
        is_published = Q(published=True)
        is_declined = Q(declined=True)
        queryset = Alert.objects.filter(symbols_match & (is_published | is_declined)).order_by('-generated_time')
        if queryset.exists():
            return queryset[0].generated_time
        return None

    @staticmethod
    def get_last_published_alert_published_time():
        is_published = Q(published=True)
        published_time_not_null = Q(published_time__isnull=False)
        queryset = Alert.objects.filter(is_published & published_time_not_null).order_by('-published_time')
        if queryset.exists():
            return queryset[0].published_time
        return None

    @staticmethod
    def get_all_validating_alerts(symbol):
        symbols_match = Q(symbol=symbol)
        not_published = Q(published=False)
        not_declined = Q(declined=False)
        return Alert.objects.filter(symbols_match & not_published & not_declined)

    @staticmethod
    def get_handicap_for_symbol(symbol, exchange_rate):
        symbol_market_cap = Alert.get_market_cap_for_symbol(symbol, exchange_rate)
        bitcoin_market_cap = Alert.get_market_cap_for_symbol('BTC', Alert.get_latest_bitcoin_exchange_rate())
        return common_utils.rectified_root(bitcoin_market_cap / symbol_market_cap, degree=4)

    @staticmethod
    def get_market_cap_for_symbol(symbol, exchange_rate):
        supply = config.SYMBOLS[symbol]['supply']
        return supply * exchange_rate

    @staticmethod
    def get_latest_bitcoin_exchange_rate():
        is_bitcoin = Q(symbol='BTC')
        is_published = Q(published=True)
        queryset = Alert.objects.filter(is_bitcoin & is_published).order_by('-published_time')
        if not queryset.exists():
            print("Warning: Using fallback Bitcoin exchange rate.")
            return config.FALLBACK_BITCOIN_EXCHANGE_RATE
        return queryset[0].current_exchange_rate


class Job(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    success = models.BooleanField(null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.delete_old_jobs()

    def delete_old_jobs(self):
        old_jobs = Job.objects.order_by('-start_time')[config.MAX_JOBS_IN_DATABASE:]
        for old_job in old_jobs:
            old_job.delete()

    def succeeded(self):
        self.end_time = datetime.datetime.now(pytz.timezone('Europe/Prague'))
        self.success = True
        self.save()

    def failed(self):
        self.end_time = datetime.datetime.now(pytz.timezone('Europe/Prague'))
        self.success = False
        self.save()

    def get_duration(self):
        if not self.end_time:
            return None
        return round((self.end_time - self.start_time).total_seconds(), 1)

alerting/views.py
from  opencoinwatch import config
from alerting.models import Alert, Job
from alerting import logic

from django.http import HttpResponse, HttpResponseBadRequest
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.views import View
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginView(View):
    def post(self, request):
        # Authentication attempt
        username = request.POST['username']
        password = request.POST['password']
        next = request.POST['next']
        user = auth.authenticate(request, username=username, password=password)

        if user is None:
            # Authentication failure
            if not User.objects.filter(username=username).exists():
                messages.add_message(request, messages.ERROR,
                                     f'User does not exist.')
            else:
                messages.add_message(request, messages.ERROR,
                                     f'Error occurred, please check your password.')
            return redirect(f'{reverse("alerting:login")}?next={next}')

        # Authentication success
        auth.login(request, user)
        if next == "":
            next = 'alerting:index'
        return redirect(next)

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('alerting:index')
        next = request.GET.get('next', '')
        template = loader.get_template('alerting/login.html')
        context = {
            'next': next,
            'production': settings.PRODUCTION,
        }
        return HttpResponse(template.render(context, request))


def logout(request):
    auth.logout(request)
    return redirect('alerting:login')


@login_required
def index(request):
    return redirect('alerting:validating')


class ValidatingView(LoginRequiredMixin, View):
    def get(self, request):
        template = loader.get_template('alerting/validating.html')
        alerts = Alert.objects.filter(published=False, declined=False)
        alerts = sorted(alerts, key=lambda alert: alert.get_importance_with_handicap(), reverse=True)
        context = {
            'user': request.user,
            'production': settings.PRODUCTION,
            'build': config.BUILD,
            'page_id': 'validating',
            'alerts': alerts,
            'validating_alerts_count': len(Alert.objects.filter(published=False, declined=False)),
            'warning_recently_published': logic.warn_recently_published(),
            'recently_published_warning_duration_minutes': config.RECENTLY_PUBLISHED_WARNING_DURATION_MINUTES,
        }
        return HttpResponse(template.render(context, request))

    def post(self, request):
        POST = self.request.POST

        alert = Alert.objects.filter(pk=POST['pk']).first()  # Returns the alert if exists, None otherwise

        if alert is None:
            messages.add_message(request, messages.ERROR, f'Invalid action, the alert was not found.')
            return redirect(reverse('alerting:validating'))
        elif not alert.is_validating():
            messages.add_message(request, messages.ERROR, f'Action not available anymore, the alert has already been processed.')
            return redirect(reverse('alerting:validating'))

        if POST['action'] == 'publish':
            alert.publish()
            messages.add_message(request, messages.SUCCESS, f'Alert was published.')
            return redirect(reverse('alerting:validating'))
        elif POST['action'] == 'decline':
            alert.decline()
            messages.add_message(request, messages.SUCCESS, f'Alert was declined.')
            return redirect(reverse('alerting:validating'))
        return HttpResponseBadRequest("400 Bad Request")


class PublishedView(LoginRequiredMixin, View):
    def get(self, request):
        template = loader.get_template('alerting/published.html')
        alerts = Alert.objects.filter(published=True).order_by('-published_time')
        context = {
            'user': request.user,
            'production': settings.PRODUCTION,
            'build': config.BUILD,
            'page_id': 'published',
            'alerts': alerts,
            'validating_alerts_count': len(Alert.objects.filter(published=False, declined=False)),
        }
        return HttpResponse(template.render(context, request))


class DeclinedView(LoginRequiredMixin, View):
    def get(self, request):
        template = loader.get_template('alerting/declined.html')
        alerts = Alert.objects.filter(declined=True).order_by('-generated_time')
        context = {
            'user': request.user,
            'production': settings.PRODUCTION,
            'build': config.BUILD,
            'page_id': 'declined',
            'alerts': alerts,
            'validating_alerts_count': len(Alert.objects.filter(published=False, declined=False)),
        }
        return HttpResponse(template.render(context, request))


class JobsView(LoginRequiredMixin, View):
    def get(self, request):
        template = loader.get_template('alerting/jobs.html')
        jobs = Job.objects.order_by('-start_time')
        context = {
            'user': request.user,
            'production': settings.PRODUCTION,
            'build': config.BUILD,
            'page_id': 'jobs',
            'jobs': jobs,
            'validating_alerts_count': len(Alert.objects.filter(published=False, declined=False)),
        }
        return HttpResponse(template.render(context, request))

alerting/templates/alerting/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet">

    <link href="{% static "alerting/css/base.css" %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light {% if not production %}non-production{% endif %}">
        <div class="container">
            <a class="navbar-brand" href="{% url 'alerting:index' %}">🪙</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if page_id == 'validating' %}active{% endif %}" href="{% url 'alerting:validating' %}">Validating<span class="badge bg-info validating-badge">{{ validating_alerts_count }}</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if page_id == 'published' %}active{% endif %}" href="{% url 'alerting:published' %}">Published</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if page_id == 'declined' %}active{% endif %}" href="{% url 'alerting:declined' %}">Declined</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if page_id == 'jobs' %}active{% endif %}" href="{% url 'alerting:jobs' %}">Jobs</a>
                    </li>
                </ul>
                <ul class="navbar-nav mr-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if page_category == 'patient-administration' %}active{% endif %}" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'alerting:logout' %}">Log out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Messages -->
    {% include 'alerting/messages.html' %}

    <!-- Content -->
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

alerting/templates/alerting/declined.html
{% extends "alerting/base.html" %}

{% block title %}
<title>Declined | 🪙 | build {{ build }}</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 p-0">
            <h4 class="mt-3 mb-4">Declined alerts</h4>
        </div>
    </div>

    {# List of alerts #}
    <div class="row">
        <div class="col">
            {% for alert in alerts %}
                <div class="card crypto-alert-card">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Timestamp: {{ alert.generated_time }} @ ${{ alert.current_exchange_rate }}</b><br>
                            <b>Reference: {{ alert.referenced_time }} @ ${{ alert.referenced_exchange_rate }}</b><br>
                            <b>Importance w. ha.: {{ alert.get_importance_with_handicap|floatformat:3 }} (basic: {{ alert.get_importance|floatformat:3 }}, handicap: {{ alert.get_handicap|floatformat:3 }}), Binance: <a href="https://www.binance.com/en/trade/{{ alert.symbol }}_USDT" target="_blank">link</a></b><br><br>
                            {{ alert.get_text }}<br>
                        </p>
                    </div>
                </div>
            {% endfor %}
            {% if not alerts %}
                No alerts to display.
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

alerting/templates/alerting/jobs.html
{% extends "alerting/base.html" %}

{% block title %}
<title>Job history ({{ validating_alerts_count }}) | 🪙 | build {{ build }}</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 p-0">
            <h4 class="mt-3 mb-4">Job history</h4>
        </div>
    </div>

    {# List of jobs #}
    <div class="row">
        <div class="col">
        {% if jobs %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Start time</th>
                        <th scope="col">End time</th>
                        <th scope="col">Duration</th>
                        <th scope="col">Success</th>
                    </tr>
                </thead>
                <tbody>
                {% for job in jobs %}
                    <tr {% if not job.success %}class="table-danger"{% endif %}>
                        <td>{{ job.start_time|date:"r" }}</td>
                        <td>{{ job.end_time|date:"r" }}</td>
                        <td>{{ job.get_duration }} s</td>
                        <td>{{ job.success }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            No jobs to display.
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

alerting/templates/alerting/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Authentication</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet">

    <link href="{% static "alerting/css/login.css" %}" rel="stylesheet">
</head>

<body class="{% if not production %}non-production{% endif %}">
    <div id="login" class="d-flex align-items-center">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <form id="login-form" class="form" action="{% url 'alerting:login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label><br>
                            <input type="text" name="username" id="username" class="form-control">
                        </div>
                        <div class="form-group mt-2 mb-3">
                            <label for="password">Password</label><br>
                            <input type="password" name="password" id="password" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" class="btn btn-primary" value="Log in">
                        </div>
                        <input type="hidden" name="next" value="{{ next }}"/>
                        {% include 'alerting/messages.html' %}
                    </form>
                </div>
            </div>
        </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

alerting/templates/alerting/messages.html
{% if messages %}
<div class="container">
{% for message in messages %}
    <div class="alert {% if message.tags == "debug" %}alert-secondary{% elif message.tags == "info" %}alert-primary{% elif message.tags == "success" %}alert-success{% elif message.tags == "warning" %}alert-warning{% elif message.tags == "error" %}alert-danger{% endif %} alert-dismissible fade show mb-0 mt-2" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
{% endfor %}
</div>
{% endif %}

alerting/templates/alerting/published.html
{% extends "alerting/base.html" %}

{% block title %}
<title>Published | 🪙 | build {{ build }}</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 p-0">
            <h4 class="mt-3 mb-4">Published alerts</h4>
        </div>
    </div>

    {# List of alerts #}
    <div class="row">
        <div class="col">
            {% for alert in alerts %}
                <div class="card crypto-alert-card">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Published: {{ alert.published_time }}</b><br>
                            <b>Timestamp: {{ alert.generated_time }} @ ${{ alert.current_exchange_rate }}</b><br>
                            <b>Reference: {{ alert.referenced_time }} @ ${{ alert.referenced_exchange_rate }}</b><br>
                            <b>Importance w. ha.: {{ alert.get_importance_with_handicap|floatformat:3 }} (basic: {{ alert.get_importance|floatformat:3 }}, handicap: {{ alert.get_handicap|floatformat:3 }}), Binance: <a href="https://www.binance.com/en/trade/{{ alert.symbol }}_USDT" target="_blank">link</a></b><br><br>
                            {{ alert.published_text }}<br>
                        </p>
                    </div>
                </div>
            {% endfor %}
            {% if not alerts %}
                No alerts to display.
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

alerting/templates/alerting/validating.html
{% extends "alerting/base.html" %}

{% block title %}
<title>Validating ({{ validating_alerts_count }}) | 🪙 | build {{ build }}</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 p-0">
            <h4 class="mt-3 mb-4">Validating alerts</h4>
        </div>
    </div>

    {# List of alerts #}
    <div class="row">
        <div class="col">
            {% if warning_recently_published %}
                <div class="alert alert-warning" role="alert">
                    <strong>An alert has been published in the last {{ recently_published_warning_duration_minutes }} minutes! Don't spam the users!</strong>
                </div>
            {% endif %}
            {% for alert in alerts %}
                {# Alert card #}
                <div class="card crypto-alert-card">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Timestamp: {{ alert.generated_time }} @ ${{ alert.current_exchange_rate }}</b><br>
                            <b>Reference: {{ alert.referenced_time }} @ ${{ alert.referenced_exchange_rate }}</b><br>
                            <b>Importance w. ha.: {{ alert.get_importance_with_handicap|floatformat:3 }} (basic: {{ alert.get_importance|floatformat:3 }}, handicap: {{ alert.get_handicap|floatformat:3 }}), Binance: <a href="https://www.binance.com/en/trade/{{ alert.symbol }}_USDT" target="_blank">link</a></b><br><br>
                            {{ alert.get_text }}<br>
                        </p>
                        <form class="d-inline" action="{% url 'alerting:validating' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="pk" value="{{ alert.pk }}">
                            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal{{ alert.pk }}">Accept and publish</button>
                            <button type="submit" class="btn btn-danger" name="action" value="decline">Decline</button>
                        </form>
                    </div>
                </div>

                {# Confirmation modal #}
                <div class="modal fade" id="modal{{ alert.pk }}" tabindex="-1">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Alert will go public. Final confirmation.</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                {% if warning_recently_published %}
                                    <div class="alert alert-warning" role="alert">
                                        <strong>Another alert has been published in the last {{ recently_published_warning_duration_minutes }} minutes. Consider delaying the publication of this alert.</strong>
                                    </div>
                                {% endif %}
                                <br>{{ alert.get_text }}<br><br>
                                <b>-----------------------------------</b><br><br>
                                <b>Timestamp: {{ alert.generated_time }} @ ${{ alert.current_exchange_rate }}</b><br>
                                <b>Reference: {{ alert.referenced_time }} @ ${{ alert.referenced_exchange_rate }}</b><br><br>
                                <b><a href="https://www.binance.com/en/trade/{{ alert.symbol }}_USDT" target="_blank">Link to Binance</a></b><br><br>
                            </div>
                            <div class="modal-footer">
                                <form class="d-inline" action="{% url 'alerting:validating' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="pk" value="{{ alert.pk }}">
                                    <button type="submit" class="btn btn-warning" name="action" value="publish">Everything is correct. I have checked Binance.</button>
                                </form>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if not alerts %}
                No alerts to display.
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}